vwiki/accounts/urls.py
from django.conf.urls import url
from . import views

app_name='accounts'
urlpatterns = [
]

vwiki/core/urls.py
from django.conf.urls import url, include
from . import views


app_name = 'core'
urlpatterns = [
  url(r'^$', views.HomeView.as_view(), name='home'),
]

vwiki/courses/urls.py
from django.conf.urls import url
from . import views

app_name='courses'
urlpatterns = [
  url(r'^(?P<course_slug>[\w_-]+)/$', views.course, name="course"),
]

vwiki/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('vwiki.core.urls')),
    url(r'^conta/', include('vwiki.accounts.urls')),
    url(r'^cursos/', include('vwiki.courses.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vwiki/accounts/models.py
from django.db import models

# Create your models here.

vwiki/courses/models.py
from django.db import models


class Category(models.Model):
  title = models.CharField('Título', max_length=100)
  icon = models.CharField('Icone', max_length=100, help_text='Icones do Font Awesome', default='fa fa-folder-open')
  created_at = models.DateTimeField('Criado em', auto_now_add=True)
  updated_at = models.DateTimeField('Modificado em', auto_now=True)

  def __str__(self):
    return self.title

  class Meta:
    verbose_name = 'Categoria'
    verbose_name_plural = 'Categorias'
    ordering = ['title']


class Course(models.Model):
  title = models.CharField('Título', max_length=100)
  slug = models.SlugField('Identificador', max_length=100)
  category = models.ForeignKey(Category, verbose_name="Categoria", related_name="courses")
  created_at = models.DateTimeField('Criado em', auto_now_add=True)
  updated_at = models.DateTimeField('Modificado em', auto_now=True)

  def __str__(self):
    return self.title

  class Meta:
    verbose_name = 'Curso'
    verbose_name_plural = 'Cursos'
    ordering = ['title']


class Topic(models.Model):
  title = models.CharField('Título', max_length=100)
  course = models.ForeignKey(Course, verbose_name="Curso", related_name="topics")
  created_at = models.DateTimeField('Criado em', auto_now_add=True)
  updated_at = models.DateTimeField('Modificado em', auto_now=True)

  def __str__(self):
    return self.title

  class Meta:
    verbose_name = 'Tópico'
    verbose_name_plural = 'Tópicos'
    ordering = ['title']


class Subtopic(models.Model):
  title = models.CharField('Título', max_length=100)
  topic = models.ForeignKey(Topic, verbose_name="Tópico", related_name="subtopics")
  created_at = models.DateTimeField('Criado em', auto_now_add=True)
  updated_at = models.DateTimeField('Modificado em', auto_now=True)

  def __str__(self):
    return self.title

  class Meta:
    verbose_name = 'Subtopico'
    verbose_name_plural = 'Subtopicos'
    ordering = ['title']


class Lesson(models.Model):
  title = models.CharField('Título', max_length=100)
  slug = models.SlugField('Identificador', max_length=100)
  content = models.TextField('Conteúdo', max_length=100)
  subtopic = models.ForeignKey(Subtopic, verbose_name="Subtopico", related_name="lessons")
  created_at = models.DateTimeField('Criado em', auto_now_add=True)
  updated_at = models.DateTimeField('Modificado em', auto_now=True)

  def __str__(self):
    return self.title

  class Meta:
    verbose_name = 'Aula'
    verbose_name_plural = 'Aulas'
    ordering = ['title']

vwiki/courses/forms.py
from django import forms
from .models import Topic


class TopicForm(forms.ModelForm):
  class Meta:
    model = Topic
    fields = ['title']

vwiki/accounts/views.py
from django.shortcuts import render

# Create your views here.

vwiki/core/views.py
from django.shortcuts import render
from django.views.generic import View
from vwiki.courses.models import Category


class HomeView(View):
  template = 'core/home.html'

  def get(self, request):
    categories = Category.objects.all()
    context = {
      'categories': categories,
    }
    return render(request, self.template, context)

vwiki/courses/views.py
from django.shortcuts import render, get_object_or_404
from .models import Course
from .forms import TopicForm


def course(request, course_slug):
  template = 'courses/course.html'
  course = get_object_or_404(Course, slug=course_slug)
  context = {'course': course}
  return render(request, template, context)


def create_topic(request, course_slug):
  template = 'courses/topic_create.html'
  course = get_object_or_404(Course, slug=course_slug)
  topic = Topic(course=course)
  form = TopicForm(request.POST or None, instance=topic)
  if form.is_valid():
    form.save()
    redirect('courses:course', kwargs=(course.id,))
  context = {'form': form}
  return render(request, template, context)

vwiki/core/templates/core/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <title>VWiki</title>
    <link rel="icon" href="https://gitlab.com/victorhad/Web/raw/43896252130a1888f67be4d59538a819099b827d/Projetos/Biografia/img/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'core/css/home.css' %}">
    {% block css %}{% endblock %}
  </head>
  <body>
    <header>
      <nav>
        <div class="nav-wrapper color">
          <a href="{% url 'core:home' %}" class="brand-logo"><i class="fa fa-home"></i>VWiki</a>
          <a href="/admin/" target="_blank" class="right login"><i class="fa fa-sign-in"></i></a>
          <a href="#" data-activates="slide-out" class="button-collapse"><i class="fa fa-bars md-20"></i></a>
        </div>
      </nav>
      <ul id="slide-out" class="side-nav fixed">
        <li>
          <div class="userView">
            <div class="background">
              <img src="http://images.freeimages.com/images/previews/85e/sunrise-1451941.jpg">
            </div>
            <img class="circle" src="{% static 'core/img/eu.jpg' %}">
            <span class="white-text name">{{user.first_name}}</span>
            <span class="white-text email">{{user.email}}</span>
          </div>
        </li>
        <ul class="collapsible" data-collapsible="accordion">
          {% block sidebar %}
            {% for category in categories %}
              <li>
                <div class="collapsible-header"><i class="{{category.icon}} left"></i>{{category.title}}</div>
                <div class="collapsible-body">
                  <div class="collection">
                    {% for course in category.courses.all %}
                      <a href="{% url 'courses:course' course.slug %}" class="collection-item">{{course.title}}</a>
                    {% endfor %}
                  </div>
                </div>
              </li>
            {% empty %}
              <p>{% trans 'There are no categories or courses registred' %}</p>
            {% endfor %}
          {% endblock %}
        </ul>
      </ul>
    </header>
    <main>
      <div class="row">
        <div class="col s12">
          {% block main %}{% endblock %}
        </div>
      </div>
    </main>
    <footer>
      <p>{% trans 'Made by' %} <a href="https://github.com/VictorArnaud">Victor Arnaud</a></p>
      {% include 'core/links.html' %}
    </footer>
    <!-- SCRIPTS -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <script type="text/javascript" async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML"></script>
    <script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});</script>
    <script src="{% static 'core/js/home.js' %}"></script>
    <script src="{% static 'core/js/search.js' %}"></script>
    {% block js %}{% endblock %}
  </body>
</html>

vwiki/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block main %}
  <div class="slider">
    <ul class="slides">
      <li>
        <img src="https://cloud.githubusercontent.com/assets/14116020/22489012/518e9b94-e7fc-11e6-8a58-38f2b5cd82c8.png">
        <div class="caption center-align">
          <h2>VWiki</h2>
          <p class="light flow-text grey-text text-lighten-3">Wiki para você inserir seus resumos de forma organizada e com um layout agradavel, podendo
            inserir categorias como Humanas, Exatas ou até Linguagens de programação, e cada categoria seus cursos e cada cursos seus tópicos
          relacionados.</p>
        </div>
      </li>
      <li>
        <img src="https://cloud.githubusercontent.com/assets/14116020/22489012/518e9b94-e7fc-11e6-8a58-38f2b5cd82c8.png">
        <div class="caption center-align">
          <h2>Disciplinas de Humanas</h2>
          <h4 class="light grey-text text-lighten-3">Disciplinas como: PDS, MDS, Requisitos, Sistemas Operacionais e etc...</h4>
        </div>
      </li>
      <li>
        <img src="https://cloud.githubusercontent.com/assets/14116020/22488931/f342d712-e7fb-11e6-8f7c-20282c9c96c1.png">
        <div class="caption left-align">
          <h2>Disciplinas de Exatas</h2>
          <h4 class="light grey-text text-lighten-3">Disciplinas como: Calculo 1 2 e 3, Algebra Linear, Fisica e etc...</h4>
        </div>
      </li>
      <li>
        <img src="https://cloud.githubusercontent.com/assets/14116020/22489159/084cc2d4-e7fd-11e6-8671-0d393f385fce.png">
        <div class="caption right-align">
          <h2>Linguagens de programação</h2>
          <h4 class="light grey-text text-lighten-3">Linguagens como: C++, Java, Python e alguns frameworks como Django e etc...</h4>
        </div>
      </li>
    </ul>
  </div>
{% endblock %}

vwiki/core/templates/core/links.html
{% load static %}
{% load i18n %}
<div class="fixed-action-btn">
  <a class="btn-floating btn-large teal darken-4 waves-effect" href="#modal"><i class="fa fa-link md-20"></i></a>
</div>
<!-- MODAL -->
<div id="modal" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h3>{% trans 'Links' %}</h3>
    <div class="input-field col s12">
      <i class="fa fa-search prefix"></i>
      <input type="text" id="searchInput" onkeyup="searchSites()" placeholder="{% trans 'Search links' %}">
    </div>
    <ul class="collapsible" data-collapsible="accordion" id="searchUL">
      <li>
        <div class="collapsible-header"><a href="https://www.udemy.com/home/my-courses/learning/" target="_blank"><i class="fa fa-link left"></i>Udemy</a></div>
        <div class="collapsible-body"><p>Cursos online de várias categorias.</p></div>
      </li>
      <li>
        <div class="collapsible-header"><a href="https://www.alura.com.br/" target="_blank"><i class="fa fa-link left"></i>Alura</a></div>
        <div class="collapsible-body"><p>Cursos online de programação, infraestrutura, design, business, mobile e front-end.</p></div>
      </li>
    </ul>
  </div>
  <div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="fa fa-close left"></i>{% trans 'Close' %}</a>
  </div>
</div>

vwiki/courses/templates/courses/course.html
{% extends 'core/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block css %}
  <link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">
{% endblock %}
{% block js %}
  <script src="{% static 'courses/js/courses.js' %}"></script>
{% endblock %}
{% block sidebar %}
  <h4 class="center-align">{{course}}</h4>
  <hr />
  {% for topic in course.topics.all %}
    {% if topic.subtopics.exists %}
      <h5>{{topic}}</h5>
      {% for subtopic in topic.subtopics.all %}
        <li>
          {% if subtopic.lessons.exists %}
            <div class="collapsible-header"><i class="fa fa-caret-down right"></i><span class="truncate">{{subtopic}}</span></div>
            <div class="collapsible-body">
              <div class="collection">
                {% for lesson in subtopic.lessons.all %}
                  <a href="#" class="collection-item truncate">{{lesson}}</a>
                {% endfor %}
              </div>
            </div>
          {% endif %}
        </li>
      {% endfor %}
    {% endif %}
  {% empty %}
    <p>{% trans 'There are no content' %}</p>
  {% endfor %}
{% endblock %}
{% block title %}Detalhes do Curso{% endblock %}
{% block main %}
<div class="card">
  <div class="card-tabs">
    <ul class="tabs tabs-fixed-width teal darken-4">
      <li class="tab"><a class="active" href="#course"><i class="fa fa-leanpub fa-padding"></i>Curso</a></li>
      <li class="tab"><a href="#topic"><i class="fa fa-plus fa-padding"></i>Adicionar Tópico</a></li>
      <li class="tab"><a href="#subtopic"><i class="fa fa-plus fa-padding"></i>Adicionar Subtópico</a></li>
      <li class="tab"><a href="#lesson"><i class="fa fa-plus fa-padding"></i>Adicionar Aula</a></li>
    </ul>
  </div>
  <div class="card-content grey lighten-4">
    <div id="course">
      <h2>{{course}}</h2>
      <hr />
      <div class="card card-description">
        <p class="flow-text">Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit
        amet aliquam vel, ullamcorper sit amet ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
        Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Nulla porttitor accumsan tincidunt. Proin eget tortor risus.
        faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.</p>
      </div>
    </div>
    <div id="topic">
      <form method="post" class="col s12">
        {% csrf_token %}
        <div class="row">
          <div class="input-field col s12">
            <input id="topic-input" type="text" name="topic" data-length="30">
            <label for="topic-input">Tópico</label>
          </div>
        </div>
        <button class="waves-effect waves-light teal darken-4 btn right" type="submit"><i class="fa fa-send-o right"></i>Salvar</button>
      </form>
    </div>
    <div id="subtopic">
      <form method="post" class="col s12">
        {% csrf_token %}
        <div class="row">
          <div class="input-field col s12">
            <input id="subtopic-input" type="text" name="subtopic" data-length="30">
            <label for="subtopic-input">Subtópico</label>
          </div>
          <div class="input-field col s12">
            <select>
              <option value="" disabled selected>Escolha um tópico</option>
              <option value="1">Topico 1</option>
              <option value="2">Topico 2</option>
              <option value="3">Topico 3</option>
            </select>
            <label>Tópico</label>
          </div>
        </div>
        <button class="waves-effect waves-light teal darken-4 btn right" type="submit"><i class="fa fa-send-o right"></i>Salvar</button>
      </form>
    </div>
    <div id="lesson">
      <form method="post" class="col s12">
        {% csrf_token %}
        <div class="row">
          <div class="input-field col s12">
            <input id="lesson-input" type="text" name="lesson" data-length="30">
            <label for="lesson-input">Aula</label>
          </div>
          <div class="input-field col s12">
            <select>
              <option value="" disabled selected>Escolha um subtópico</option>
              <option value="1">Subtopico 1</option>
              <option value="2">Subtopico 2</option>
              <option value="3">Subtopico 3</option>
            </select>
            <label>Subtópico</label>
          </div>
        </div>
        <button class="waves-effect waves-light teal darken-4 btn right" type="submit"><i class="fa fa-send-o right"></i>Salvar</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}